# SPDX-License-Identifier: GPL-2.0+


dtb-$(CONFIG_TARGET_SMDKC100) += s5pc1xx-smdkc100.dtb
dtb-$(CONFIG_TARGET_S5P_GONI) += s5pc1xx-goni.dtb

dtb-$(CONFIG_TARGET_HIKEY) += hi6220-hikey.dtb
dtb-$(CONFIG_TARGET_HIKEY960) += hi3660-hikey960.dtb

dtb-$(CONFIG_TARGET_POPLAR) += hi3798cv200-poplar.dtb

dtb-$(CONFIG_ARCH_APPLE) += \
	t8103-j274.dtb \
	t8103-j293.dtb \
	t8103-j313.dtb \
	t8103-j456.dtb \
	t8103-j457.dtb

dtb-$(CONFIG_ARCH_DAVINCI) += \
	da850-evm.dtb \
	da850-lcdk.dtb \
	da850-lego-ev3.dtb

dtb-$(CONFIG_MACH_S900) += \
	bubblegum_96.dtb
dtb-$(CONFIG_MACH_S700) += \
	s700-cubieboard7.dtb

dtb-$(CONFIG_ROCKCHIP_PX30) += \
	px30-evb.dtb \
	px30-firefly.dtb \
	px30-engicam-px30-core-ctouch2.dtb \
	px30-engicam-px30-core-ctouch2-of10.dtb \
	px30-engicam-px30-core-edimm2.2.dtb \
	rk3326-odroid-go2.dtb


dtb-$(CONFIG_ROCKCHIP_RV1108) += \
	rv1108-elgin-r1.dtb \
	rv1108-evb.dtb

dtb-$(CONFIG_ROCKCHIP_RV1126) += \
	rv1126-edgeble-neu2-io.dtb

dtb-$(CONFIG_ARCH_S5P4418) += \
	s5p4418-nanopi2.dtb



dtb-$(CONFIG_ARCH_SYNQUACER) += synquacer-sc2a11-developerbox.dtb


dtb-$(CONFIG_TARGET_THUNDERX_88XX) += thunderx-88xx.dtb


dtb-$(CONFIG_TARGET_DRA7XX_EVM) += dra72-evm.dtb dra7-evm.dtb	\
	dra72-evm-revc.dtb dra71-evm.dtb dra76-evm.dtb
dtb-$(CONFIG_TARGET_AM57XX_EVM) += am57xx-beagle-x15.dtb \
	am57xx-beagle-x15-revb1.dtb \
	am57xx-beagle-x15-revc.dtb \
	am5729-beagleboneai.dtb \
	am574x-idk.dtb \
	am572x-idk.dtb	\
	am571x-idk.dtb
dtb-$(CONFIG_TARGET_STV0991) += stv0991.dtb

dtb-$(CONFIG_ARCH_LS1021A) += ls1021a-qds-duart.dtb \
	ls1021a-qds-lpuart.dtb \
	ls1021a-twr-duart.dtb ls1021a-twr-lpuart.dtb \
	ls1021a-iot-duart.dtb ls1021a-tsn.dtb
dtb-$(CONFIG_TARGET_PG_WCOM_SELI8) += ls1021a-pg-wcom-seli8.dtb
dtb-$(CONFIG_TARGET_PG_WCOM_EXPU1) += ls1021a-pg-wcom-expu1.dtb

dtb-$(CONFIG_FSL_LSCH3) += fsl-ls2080a-qds.dtb \
	fsl-ls2080a-qds-42-x.dtb \
	fsl-ls2080a-rdb.dtb \
	fsl-ls2081a-rdb.dtb \
	fsl-ls2088a-rdb-qspi.dtb \
	fsl-ls1088a-rdb.dtb \
	fsl-ls1088a-qds.dtb \
	fsl-ls1088a-qds-21-x.dtb \
	fsl-ls1088a-qds-29-x.dtb \
	fsl-ls1028a-rdb.dtb \
	fsl-ls1028a-qds-duart.dtb \
	fsl-ls1028a-qds-lpuart.dtb \
	fsl-lx2160a-rdb.dtb \
	fsl-lx2160a-qds.dtb \
	fsl-lx2160a-qds-3-x-x.dtb \
	fsl-lx2160a-qds-3-11-x.dtb \
	fsl-lx2160a-qds-7-x-x.dtb \
	fsl-lx2160a-qds-7-11-x.dtb \
	fsl-lx2160a-qds-19-x-x.dtb \
	fsl-lx2160a-qds-19-11-x.dtb \
	fsl-lx2160a-qds-20-x-x.dtb \
	fsl-lx2160a-qds-20-11-x.dtb \
	fsl-lx2160a-qds-13-x-x.dtb \
	fsl-lx2160a-qds-14-x-x.dtb \
	fsl-lx2162a-qds.dtb\
	fsl-lx2162a-qds-17-x.dtb\
	fsl-lx2162a-qds-18-x.dtb\
	fsl-lx2162a-qds-20-x.dtb
dtb-$(CONFIG_FSL_LSCH2) += fsl-ls1043a-qds-duart.dtb \
	fsl-ls1043a-qds-lpuart.dtb \
	fsl-ls1043a-rdb.dtb \
	fsl-ls1046a-qds-duart.dtb \
	fsl-ls1046a-qds-lpuart.dtb \
	fsl-ls1046a-rdb.dtb \
	fsl-ls1046a-frwy.dtb \
	fsl-ls1012a-qds.dtb \
	fsl-ls1012a-rdb.dtb \
	fsl-ls1012a-2g5rdb.dtb \
	fsl-ls1012a-frdm.dtb \
	fsl-ls1012a-frwy.dtb
dtb-$(CONFIG_TARGET_SL28) += fsl-ls1028a-kontron-sl28.dtb \
	fsl-ls1028a-kontron-sl28-var1.dtb \
	fsl-ls1028a-kontron-sl28-var2.dtb \
	fsl-ls1028a-kontron-sl28-var3.dtb \
	fsl-ls1028a-kontron-sl28-var4.dtb \

dtb-$(CONFIG_TARGET_TEN64) += fsl-ls1088a-ten64.dtb

dtb-$(CONFIG_TARGET_DRAGONBOARD410C) += dragonboard410c.dtb
dtb-$(CONFIG_TARGET_DRAGONBOARD820C) += dragonboard820c.dtb
dtb-$(CONFIG_TARGET_STARQLTECHN) += starqltechn.dtb
dtb-$(CONFIG_TARGET_QCS404EVB) += qcs404-evb.dtb

dtb-$(CONFIG_TARGET_STEMMY) += ste-ux500-samsung-stemmy.dtb


dtb-$(CONFIG_VF610) += vf610-colibri-eval-v3.dtb \
	vf610-twr.dtb \
	vf610-pcm052.dtb \
	vf610-bk4r1.dtb

dtb-$(CONFIG_MX23) += \
	imx23-evk.dtb

dtb-$(CONFIG_TARGET_MX23_OLINUXINO) += \
	imx23-olinuxino.dtb

dtb-$(CONFIG_MX28) += \
	imx28-evk.dtb \
	imx28-xea.dtb

dtb-$(CONFIG_MX51) += \
	imx51-babbage.dtb

dtb-$(CONFIG_MX53) += imx53-cx9020.dtb \
	imx53-qsb.dtb \
	imx53-kp.dtb \
	imx53-m53menlo.dtb \
	imx53-usbarmory.dtb

ifneq ($(CONFIG_MX6DL)$(CONFIG_MX6QDL)$(CONFIG_MX6S),)
dtb-y += \
	imx6dl-aristainetos2c_7.dtb \
	imx6dl-aristainetos2c_cslb_7.dtb \
	imx6dl-brppt2.dtb \
	imx6dl-cubox-i.dtb \
	imx6dl-cubox-i-emmc-som-v15.dtb \
	imx6dl-cubox-i-som-v15.dtb \
	imx6dl-dhcom-pdk2.dtb \
	imx6dl-dhcom-picoitx.dts \
	imx6dl-gw51xx.dtb \
	imx6dl-gw52xx.dtb \
	imx6dl-gw53xx.dtb \
	imx6dl-gw54xx.dtb \
	imx6dl-gw551x.dtb \
	imx6dl-gw552x.dtb \
	imx6dl-gw553x.dtb \
	imx6dl-gw560x.dtb \
	imx6dl-gw5903.dtb \
	imx6dl-gw5904.dtb \
	imx6dl-gw5907.dtb \
	imx6dl-gw5910.dtb \
	imx6dl-gw5912.dtb \
	imx6dl-gw5913.dtb \
	imx6dl-hummingboard2.dtb \
	imx6dl-hummingboard2-emmc-som-v15.dtb \
	imx6dl-hummingboard2-som-v15.dtb \
	imx6dl-hummingboard.dtb \
	imx6dl-hummingboard-emmc-som-v15.dtb \
	imx6dl-hummingboard-som-v15.dtb \
	imx6dl-icore.dtb \
	imx6dl-icore-mipi.dtb \
	imx6dl-icore-rqs.dtb \
	imx6dl-mba6a.dtb \
	imx6dl-mba6b.dtb \
	imx6dl-mamoj.dtb \
	imx6dl-nitrogen6x.dtb \
	imx6dl-pico.dtb \
	imx6dl-udoo.dtb \
	imx6dl-riotboard.dtb \
	imx6dl-sabreauto.dtb \
	imx6dl-sabreauto-ecspi.dtb \
	imx6dl-sabreauto-gpmi-weim.dtb \
	imx6dl-sabresd.dtb \
	imx6dl-sielaff.dtb \
	imx6dl-edm.dtb \
	imx6dl-wandboard-revd1.dtb \
	imx6s-dhcom-drc02.dtb

endif

ifneq ($(CONFIG_MX6Q)$(CONFIG_MX6QDL)$(CONFIG_MX6QP),)
dtb-y += \
	imx6q-apalis-eval.dtb \
	imx6q-bosch-acc.dtb \
	imx6q-cm-fx6.dtb \
	imx6q-cubox-i.dtb \
	imx6q-cubox-i-emmc-som-v15.dtb \
	imx6q-cubox-i-som-v15.dtb \
	imx6q-dhcom-pdk2.dtb \
	imx6q-display5.dtb \
	imx6q-gw51xx.dtb \
	imx6q-gw52xx.dtb \
	imx6q-gw53xx.dtb \
	imx6q-gw54xx.dtb \
	imx6q-gw551x.dtb \
	imx6q-gw552x.dtb \
	imx6q-gw553x.dtb \
	imx6q-gw560x.dtb \
	imx6q-gw5903.dtb \
	imx6q-gw5904.dtb \
	imx6q-gw5907.dtb \
	imx6q-gw5910.dtb \
	imx6q-gw5912.dtb \
	imx6q-gw5913.dtb \
	imx6q-hummingboard2.dtb \
	imx6q-hummingboard2-emmc-som-v15.dtb \
	imx6q-hummingboard2-som-v15.dtb \
	imx6q-hummingboard.dtb \
	imx6q-hummingboard-emmc-som-v15.dtb \
	imx6q-hummingboard-som-v15.dtb \
	imx6q-icore.dtb \
	imx6q-icore-mipi.dtb \
	imx6q-icore-rqs.dtb \
	imx6q-kp.dtb \
	imx6q-logicpd.dtb \
	imx6q-marsboard.dtb \
	imx6q-mba6a.dtb \
	imx6q-mba6b.dtb \
	imx6q-mccmon6.dtb\
	imx6q-nitrogen6x.dtb \
	imx6q-novena.dtb \
	imx6q-pico.dtb \
	imx6q-phytec-mira-rdk-nand.dtb \
	imx6q-udoo.dtb \
	imx6q-sabreauto.dtb \
	imx6q-sabreauto-ecspi.dtb \
	imx6q-sabreauto-gpmi-weim.dtb \
	imx6q-sabrelite.dtb \
	imx6q-sabresd.dtb \
	imx6q-tbs2910.dtb \
	imx6q-edm.dtb \
	imx6q-wandboard-revd1.dtb \
	imx6qp-sabreauto.dtb \
	imx6qp-sabreauto-ecspi.dtb \
	imx6qp-sabreauto-gpmi-weim.dtb \
	imx6qp-sabresd.dtb \
	imx6qp-edm.dtb \
	imx6qp-wandboard-revd1.dtb \

endif

dtb-$(CONFIG_MX6SL) += imx6sl-evk.dtb

dtb-$(CONFIG_MX6SLL) += imx6sll-evk.dtb

dtb-$(CONFIG_MX6SX) += \
	imx6sx-sabreauto.dtb \
	imx6sx-sdb.dtb \
	imx6sx-sdb-emmc.dtb \
	imx6sx-softing-vining-2000.dtb \
	imx6sx-udoo-neo-basic.dtb \
	imx6sx-udoo-neo-extended.dtb \
	imx6sx-udoo-neo-full.dtb

dtb-$(CONFIG_MX6UL) += \
	imx6ul-geam.dtb \
	imx6ul-isiot-emmc.dtb \
	imx6ul-isiot-nand.dtb \
	imx6ul-opos6uldev.dtb \
	imx6ul-14x14-evk.dtb \
	imx6ul-14x14-evk-emmc.dtb \
	imx6ul-14x14-evk-gpmi-weim.dtb \
	imx6ul-9x9-evk.dtb \
	imx6ul-liteboard.dtb \
	imx6ul-phytec-segin-ff-rdk-nand.dtb \
	imx6ul-pico-hobbit.dtb \
	imx6ul-pico-pi.dtb \
	imx6ul-kontron-bl.dtb \
	imx6ull-kontron-bl.dtb

dtb-$(CONFIG_MX6ULL) += \
	imx6ull-14x14-evk.dtb \
	imx6ull-14x14-evk-emmc.dtb \
	imx6ull-14x14-evk-gpmi-weim.dtb \
	imx6ull-9x9-evk.dtb \
	imx6ull-colibri-emmc-eval-v3.dtb \
	imx6ull-colibri-eval-v3.dtb \
	imx6ull-myir-mys-6ulx-eval.dtb \
	imx6ull-seeed-npi-imx6ull-dev-board.dtb \
	imx6ull-phytec-segin-ff-rdk-emmc.dtb \
	imx6ull-dart-6ul.dtb \
	imx6ull-somlabs-visionsom.dtb \
	imx6ulz-bsh-smm-m2.dtb \
	imx6ulz-14x14-evk.dtb \
	imx6ulz-14x14-evk-emmc.dtb \
	imx6ulz-14x14-evk-gpmi-weim.dtb

dtb-$(CONFIG_ARCH_MX6) += \
	imx6q-apalis-eval.dtb \
	imx6dl-colibri-eval-v3.dtb

dtb-$(CONFIG_O4_IMX_NANO) += \
	o4-imx-nano.dtb

dtb-$(CONFIG_EV_IMX280_NANO_X_MB) += \
	ev-imx280-nano-x-mb.dtb

dtb-$(CONFIG_MX7) += imx7d-sdb.dtb \
	imx7d-sdb-qspi.dtb \
	imx7d-sdb-epdc.dtb \
	imx7d-sdb-gpmi-weim.dtb \
	imx7d-sdb-reva.dtb \
	imx7-cm.dtb \
	imx7d-colibri-emmc-eval-v3.dtb \
	imx7d-colibri-eval-v3.dtb \
	imx7s-warp.dtb \
	imx7d-meerkat96.dtb \
	imx7d-pico-pi.dtb \
	imx7d-pico-hobbit.dtb \
	imx7d-smegw01.dtb \
	imx7d-tep1-a2.dtb \
	imx7d-12x12-lpddr3-val.dtb \
	imx7d-12x12-lpddr3-val-ecspi.dtb \
	imx7d-12x12-lpddr3-val-qspi.dtb \
	imx7d-12x12-ddr3-val.dtb \
	imx7d-19x19-ddr3-val.dtb \
	imx7d-19x19-lpddr2-val.dtb \
	imx7d-19x19-lpddr3-val.dtb

dtb-$(CONFIG_ARCH_MX7ULP) += imx7ulp-com.dtb \
	imx7ulp-evk.dtb \
	imx7ulp-evk-emmc.dtb \
	imx7ulp-evk-qspi.dtb

dtb-$(CONFIG_ARCH_HIGHBANK) += highbank.dtb

dtb-$(CONFIG_ARCH_IMX8) += \
	fsl-imx8qm-apalis.dtb \
	fsl-imx8qm-mek.dtb \
	fsl-imx8qm-ddr4-val.dtb \
	fsl-imx8qm-lpddr4-val.dtb \
	fsl-imx8qm-mek-cockpit-a53.dtb \
	fsl-imx8qm-mek-cockpit-a72.dtb \
	imx8qm-cgtqmx8.dtb \
	imx8qm-dmsse20-a1.dtb \
	imx8qm-rom7720-a1.dtb \
	fsl-imx8qxp-ai_ml.dtb \
	fsl-imx8qxp-colibri.dtb \
	fsl-imx8qxp-mek.dtb \
	fsl-imx8qxp-lpddr4-val.dtb \
	fsl-imx8qxp-lpddr4-val-gpmi-nand.dtb \
	fsl-imx8qxp-17x17-val.dtb \
	fsl-imx8dx-17x17-val.dtb \
	fsl-imx8dx-mek.dtb \
	fsl-imx8dxl-evk.dtb \
	fsl-imx8dxl-evk-lcdif.dtb \
	fsl-imx8dxl-ddr3l-evk.dtb \
	imx8-deneb.dtb \
	imx8-giedi.dtb

dtb-$(CONFIG_ARCH_IMX8ULP) += \
	imx8ulp-evk.dtb \
	imx8ulp-evk-i3c.dtb \
	imx8ulp-9x9-evk.dtb \
	imx8ulp-9x9-evk-i3c.dtb \
	imx8ulp-watch.dtb

dtb-$(CONFIG_ARCH_IMX8M) += \
	imx8mm-data-modul-edm-sbc.dtb \
	imx8mm-ddr4-evk.dtb \
	imx8mm-ddr4-ab2.dtb \
	imx8mm-evk.dtb \
	imx8mm-ab2.dtb \
	imx8mm-icore-mx8mm-ctouch2.dtb \
	imx8mm-icore-mx8mm-edimm2.2.dtb \
	imx8mm-kontron-bl.dtb \
	imx8mm-kontron-bl-osm-s.dtb \
	imx8mm-mx8menlo.dtb \
	imx8mm-phg.dtb \
	imx8mm-phyboard-polis-rdk.dtb \
	imx8mm-phygate-tauri-l.dtb \
	imx8mm-venice.dtb \
	imx8mm-venice-gw71xx-0x.dtb \
	imx8mm-venice-gw72xx-0x.dtb \
	imx8mm-venice-gw73xx-0x.dtb \
	imx8mm-venice-gw7901.dtb \
	imx8mm-venice-gw7902.dtb \
	imx8mm-venice-gw7903.dtb \
	imx8mm-venice-gw7904.dtb \
	imx8mm-venice-gw7905-0x.dtb \
	imx8mm-pico-pi.dtb \
	imx8mm-pico-wizard.dtb \
	imx8mm-edm-g-wb.dtb \
	imx8mm-verdin-wifi-dev.dtb \
	imx8mn-bsh-smm-s2.dtb \
	imx8mn-bsh-smm-s2pro.dtb \
	imx8mn-ddr3l-evk.dtb \
	imx8mn-ddr4-evk.dtb \
	imx8mn-ddr4-ab2.dtb \
	imx8mq-cm.dtb \
	imx8mn-evk.dtb \
	imx8mn-ab2.dtb \
	imx8mn-edm-g.dtb \
	imx8mn-var-som-symphony.dtb \
	imx8mn-venice.dtb \
	imx8mn-venice-gw7902.dtb \
	imx8mq-edm-wizard.dtb \
	imx8mq-evk.dtb \
	imx8mm-beacon-kit.dtb \
	imx8mn-beacon-kit.dtb \
	imx8mq-mnt-reform2.dtb \
	imx8mq-phanbell.dtb \
	imx8mp-axon.dtb \
	imx8mp-beacon-kit.dtb \
	imx8mp-data-modul-edm-sbc.dtb \
	imx8mp-dhcom-som-overlay-rev100.dtbo \
	imx8mp-dhcom-som-overlay-eth1xfast.dtbo \
	imx8mp-dhcom-som-overlay-eth2xfast.dtbo \
	imx8mp-dhcom-pdk-overlay-eth2xfast.dtbo \
	imx8mp-debix-model-a.dtb \
	imx8mp-dhcom-pdk2.dtb \
	imx8mp-dhcom-pdk3.dtb \
	imx8mp-dhcom-pdk3-overlay-rev100.dtbo \
	imx8mp-edm-g.dtb \
	imx8mp-sc.dtb \
	imx8mp-tek.dtb \
	imx8mp-tep.dtb \
	imx8mp-ddr4-evk.dtb \
	imx8mp-evk.dtb \
	imx8mp-icore-mx8mp-edimm2.2.dtb \
	imx8mp-msc-sm2s.dtb \
	imx8mp-phyboard-pollux-rdk.dtb \
	imx8mp-venice.dtb \
	imx8mp-venice-gw71xx-2x.dtb \
	imx8mp-venice-gw72xx-2x.dtb \
	imx8mp-venice-gw73xx-2x.dtb \
	imx8mp-venice-gw74xx.dtb \
	imx8mp-venice-gw7905-2x.dtb \
	imx8mp-verdin-wifi-dev.dtb \
	imx8mp-navqp.dtb \
	imx8mq-pico-pi.dtb \
	imx8mq-pico-wizard.dtb \
	imx8mq-kontron-pitx-imx8m.dtb \
	imx8mq-librem5-r4.dtb

dtb-$(CONFIG_ARCH_IMX9) += \
	imx95-15x15-evk.dtb \
	imx95-19x19-evk.dtb \
	imx95-19x19-verdin.dtb \
	imx91-11x11-evk.dtb \
	imx91-9x9-qsb.dtb \
	imx91-11x11-evk-spinand.dtb \
	imx91-11x11-evk-tianma-wvga-panel.dtb \
	imx93-11x11-evk.dtb \
	imx93-11x11-evk-pmic-pf0900.dtb \
	imx93-14x14-evk.dtb \
	imx93-9x9-qsb.dtb \
	imx93-9x9-qsb-ontat-wvga-panel.dtb \
	imx93-axon.dtb \
	imx93-edm.dtb \
	imx93-var-som-symphony.dtb \
	imx93-phyboard-segin.dtb

dtb-$(CONFIG_ARCH_IMXRT) += imxrt1050-evk.dtb \
	imxrt1020-evk.dtb \
	imxrt1170-evk.dtb \

dtb-$(CONFIG_TARGET_RZG2L) += \
	r9a07g044l2-smarc.dts

ifdef CONFIG_RCAR_64
DTC_FLAGS += -R 4 -p 0x1000
endif

dtb-$(CONFIG_RZA1) += \
	r7s72100-gr-peach-u-boot.dtb

dtb-$(CONFIG_ARCH_KEYSTONE) += keystone-k2hk-evm.dtb \
	keystone-k2l-evm.dtb \
	keystone-k2e-evm.dtb \
	keystone-k2g-evm.dtb \
	keystone-k2g-generic.dtb \
	keystone-k2g-ice.dtb


dtb-$(CONFIG_TARGET_ETHERNUT5) += ethernut5.dtb

dtb-$(CONFIG_TARGET_USB_A9263) += usb_a9263.dtb

dtb-$(CONFIG_TARGET_OMAP3_LOGIC) += \
	logicpd-som-lv-35xx-devkit.dtb \
	logicpd-som-lv-37xx-devkit.dtb \
	logicpd-torpedo-35xx-devkit.dtb \
	logicpd-torpedo-37xx-devkit.dtb

dtb-$(CONFIG_TARGET_OMAP3_EVM) += \
	omap3-evm-37xx.dtb \
	omap3-evm.dtb

dtb-$(CONFIG_TARGET_OMAP3_BEAGLE) += \
	omap3-beagle-xm-ab.dtb \
	omap3-beagle-xm.dtb \
	omap3-beagle.dtb

dtb-$(CONFIG_TARGET_DEVKIT8000) += omap3-devkit8000.dtb

dtb-$(CONFIG_TARGET_OMAP3_IGEP00X0) += \
	omap3-igep0020.dtb

dtb-$(CONFIG_TARGET_OMAP4_PANDA) += \
	omap4-panda.dtb \
	omap4-panda-es.dtb

dtb-$(CONFIG_TARGET_OMAP4_SDP4430) += \
	omap4-sdp.dtb \
	omap4-sdp-es23plus.dtb


dtb-$(CONFIG_TARGET_SAMA5D3XEK) += \
	sama5d31ek.dtb \
	sama5d33ek.dtb \
	sama5d34ek.dtb \
	sama5d35ek.dtb \
	sama5d36ek.dtb \
	sama5d36ek_cmp.dtb

dtb-$(CONFIG_ARCH_STI) += stih410-b2260.dtb


dtb-$(CONFIG_ARCH_MEDIATEK) += \
	mt7622-rfb.dtb \
	mt7623a-unielec-u7623-02-emmc.dtb \
	mt7622-bananapi-bpi-r64.dtb \
	mt7623n-bananapi-bpi-r2.dtb \
	mt7629-rfb.dtb \
	mt7981-rfb.dtb \
	mt7981-emmc-rfb.dtb \
	mt7981-sd-rfb.dtb \
	mt7986a-bpi-r3-sd.dtb \
	mt7986a-bpi-r3-emmc.dtb \
	mt7986a-rfb.dtb \
	mt7986b-rfb.dtb \
	mt7986a-sd-rfb.dtb \
	mt7986b-sd-rfb.dtb \
	mt7986a-emmc-rfb.dtb \
	mt7986b-emmc-rfb.dtb \
	mt7988-rfb.dtb \
	mt7988-sd-rfb.dtb \
	mt8183-pumpkin.dtb \
	mt8512-bm1-emmc.dtb \
	mt8516-pumpkin.dtb \
	mt8518-ap1-emmc.dtb

dtb-$(CONFIG_ARCH_NPCM7xx) += nuvoton-npcm750-evb.dtb
dtb-$(CONFIG_ARCH_NPCM8XX) += nuvoton-npcm845-evb.dtb
dtb-$(CONFIG_XEN) += xenguest-arm64.dtb

dtb-$(CONFIG_ARCH_OCTEONTX) += octeontx.dtb
dtb-$(CONFIG_ARCH_OCTEONTX2) += octeontx.dtb

dtb-$(CONFIG_TARGET_GE_BX50V3) += \
	imx6q-bx50v3.dtb \
	imx6q-b850v3.dtb \
	imx6q-b650v3.dtb \
	imx6q-b450v3.dtb

dtb-$(CONFIG_TARGET_GE_B1X5V2) += imx6dl-b1x5v2.dtb
dtb-$(CONFIG_TARGET_MX53PPD) += imx53-ppd.dtb

# TODO(Linus Walleij <linus.walleij@linaro.org>): Should us a single vexpress
# Kconfig option to build all of these. See examples above.
dtb-$(CONFIG_TARGET_VEXPRESS_CA9X4) += vexpress-v2p-ca9.dtb
dtb-$(CONFIG_TARGET_VEXPRESS64_BASE_FVP) += fvp-base-revc.dtb
dtb-$(CONFIG_TARGET_VEXPRESS64_BASER_FVP) += arm_fvp.dtb
dtb-$(CONFIG_TARGET_VEXPRESS64_JUNO) += juno-r2.dtb

dtb-$(CONFIG_TARGET_TOTAL_COMPUTE) += total_compute.dtb

dtb-$(CONFIG_TARGET_DURIAN) += phytium-durian.dtb
dtb-$(CONFIG_TARGET_POMELO) += phytium-pomelo.dtb
dtb-$(CONFIG_TARGET_PE2201) += phytium-pe2201.dtb

dtb-$(CONFIG_TARGET_PRESIDIO_ASIC) += ca-presidio-engboard.dtb

dtb-$(CONFIG_TARGET_GXP) += hpe-bmc-dl360gen10.dts

dtb-$(CONFIG_TARGET_IMX8MM_CL_IOT_GATE) += imx8mm-cl-iot-gate.dtb \
					imx8mm-cl-iot-gate-ied.dtbo \
					imx8mm-cl-iot-gate-ied-adc0.dtbo \
					imx8mm-cl-iot-gate-ied-adc1.dtbo \
					imx8mm-cl-iot-gate-ied-can0.dtbo \
					imx8mm-cl-iot-gate-ied-can1.dtbo \
					imx8mm-cl-iot-gate-ied-tpm0.dtbo \
					imx8mm-cl-iot-gate-ied-tpm1.dtbo

dtb-$(CONFIG_TARGET_IMX8MM_CL_IOT_GATE_OPTEE) += imx8mm-cl-iot-gate-optee.dtb \
					imx8mm-cl-iot-gate-ied.dtbo \
					imx8mm-cl-iot-gate-ied-adc0.dtbo \
					imx8mm-cl-iot-gate-ied-adc1.dtbo \
					imx8mm-cl-iot-gate-ied-can0.dtbo \
					imx8mm-cl-iot-gate-ied-can1.dtbo \
					imx8mm-cl-iot-gate-ied-tpm0.dtbo \
					imx8mm-cl-iot-gate-ied-tpm1.dtbo

ifneq ($(CONFIG_TARGET_IMX8MP_RSB3720A1_4G)$(CONFIG_TARGET_IMX8MP_RSB3720A1_6G),)
dtb-y += imx8mp-rsb3720-a1.dtb
endif

dtb-$(CONFIG_TARGET_EA_LPC3250DEVKITV2) += lpc3250-ea3250.dtb

dtb-$(CONFIG_ARCH_QEMU) += qemu-arm.dtb qemu-arm64.dtb

dtb-$(CONFIG_TARGET_CORSTONE1000) += corstone1000-mps3.dtb \
				corstone1000-fvp.dtb

include $(srctree)/scripts/Makefile.dts

targets += $(dtb-y)

# Add any required device tree compiler flags here
DTC_FLAGS += -a 0x8

DTC_FLAGS_imx8mp-dhcom-pdk3-overlay-rev100 += -Wno-avoid_default_addr_size -Wno-reg_format

PHONY += dtbs
dtbs: $(addprefix $(obj)/, $(dtb-y))
	@:

clean-files := *.dtb *.dtbo *_HS
